* Forecast Server

This "forecasting server" is a single POST endpoint server that, given json-formatted price history for equities, returns a linearly extrapolated price prediction.
** Running
This project was developed to run on python 3.7.10. Users can run the server by first cloning the repo, then running the following in their terminal:

#+begin_src
  pip install -r requirements.txt
  python server.py
#+end_src

Then, users can run post commands such as

#+begin_src
curl localhost:8000 -X POST -H "Content-Type: application/json" -d '{"US Equity 1": {"2019-12-31 00:00:00": 1, "2020-01-01 00:00:00": 2, "2020-01-02 00:00:00": 3, "2020-01-03 00:00:00": 4}}'  
#+end_src

The test.sh file has a couple test cases for various price histories. This can be used by running the following in the terminal:

#+begin_src
  chmod +x test.sh
  ./test.sh
#+end_src

Finally, results are logged in the "forecasts.log" file.

** Implementation

The implementation for this server is straight forward. First, there is a default post endpoint for the server (build with aiohttp) that takes in data.

Then, for each equity in the data payload, the prices are extracted, a linear regression model is trained, and the next price is predicted. Additionally, the next buisness day is calculated, and this buisness day and price pair is returned to the user.

There are also checks on the data format, and logging commands to save server history.
